In [18]:
import sys, os
sys.path.append(os.path.abspath(os.path.join('..')))

In [19]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scripts.dataloader import DataLoader
from scripts.data_understanding import DataUnderstanding

In [20]:
dl = DataLoader('../data', 'data.csv')
df = dl.read_csv()
du = DataUnderstanding(df)

In [21]:
du.pick_data(5)

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [22]:
df.columns.tolist()

['Bearer Id',
 'Start',
 'Start ms',
 'End',
 'End ms',
 'Dur. (ms)',
 'IMSI',
 'MSISDN/Number',
 'IMEI',
 'Last Location Name',
 'Avg RTT DL (ms)',
 'Avg RTT UL (ms)',
 'Avg Bearer TP DL (kbps)',
 'Avg Bearer TP UL (kbps)',
 'TCP DL Retrans. Vol (Bytes)',
 'TCP UL Retrans. Vol (Bytes)',
 'DL TP < 50 Kbps (%)',
 '50 Kbps < DL TP < 250 Kbps (%)',
 '250 Kbps < DL TP < 1 Mbps (%)',
 'DL TP > 1 Mbps (%)',
 'UL TP < 10 Kbps (%)',
 '10 Kbps < UL TP < 50 Kbps (%)',
 '50 Kbps < UL TP < 300 Kbps (%)',
 'UL TP > 300 Kbps (%)',
 'HTTP DL (Bytes)',
 'HTTP UL (Bytes)',
 'Activity Duration DL (ms)',
 'Activity Duration UL (ms)',
 'Dur. (ms).1',
 'Handset Manufacturer',
 'Handset Type',
 'Nb of sec with 125000B < Vol DL',
 'Nb of sec with 1250B < Vol UL < 6250B',
 'Nb of sec with 31250B < Vol DL < 125000B',
 'Nb of sec with 37500B < Vol UL',
 'Nb of sec with 6250B < Vol DL < 31250B',
 'Nb of sec with 6250B < Vol UL < 37500B',
 'Nb of sec with Vol DL < 6250B',
 'Nb of sec with Vol UL < 1250B',
 'Social Media DL (Bytes)',
 'Social Media UL (Bytes)',
 'Google DL (Bytes)',
 'Google UL (Bytes)',
 'Email DL (Bytes)',
 'Email UL (Bytes)',
 'Youtube DL (Bytes)',
 'Youtube UL (Bytes)',
 'Netflix DL (Bytes)',
 'Netflix UL (Bytes)',
 'Gaming DL (Bytes)',
 'Gaming UL (Bytes)',
 'Other DL (Bytes)',
 'Other UL (Bytes)',
 'Total UL (Bytes)',
 'Total DL (Bytes)']

# Handling Missing Values

In [23]:
from scripts.utils import Utils
util = Utils()

In [24]:
missing_table = util.missing_values_table(df)

In [25]:
missing_table

,Missing Values,% of Total Values,Dtype
Nb of sec with 37500B < Vol UL,130254,86.8,float64
Nb of sec with 6250B < Vol UL < 37500B,111843,74.6,float64
Nb of sec with 125000B < Vol DL,97538,65.0,float64
TCP UL Retrans. Vol (Bytes),96649,64.4,float64
Nb of sec with 31250B < Vol DL < 125000B,93586,62.4,float64
Nb of sec with 1250B < Vol UL < 6250B,92894,61.9,float64
Nb of sec with 6250B < Vol DL < 31250B,88317,58.9,float64
TCP DL Retrans. Vol (Bytes),88146,58.8,float64
HTTP UL (Bytes),81810,54.5,float64
HTTP DL (Bytes),81474,54.3,float64
Avg RTT DL (ms),27829,18.6,float64
Avg RTT UL (ms),27812,18.5,float64
Last Location Name,1153,0.8,object
MSISDN/Number,1066,0.7,float64
Bearer Id,991,0.7,float64
Nb of sec with Vol UL < 1250B,793,0.5,float64
10 Kbps < UL TP < 50 Kbps (%),792,0.5,float64
UL TP > 300 Kbps (%),792,0.5,float64
50 Kbps < UL TP < 300 Kbps (%),792,0.5,float64
UL TP < 10 Kbps (%),792,0.5,float64
Nb of sec with Vol DL < 6250B,755,0.5,float64
250 Kbps < DL TP < 1 Mbps (%),754,0.5,float64
50 Kbps < DL TP < 250 Kbps (%),754,0.5,float64
DL TP < 50 Kbps (%),754,0.5,float64
DL TP > 1 Mbps (%),754,0.5,float64
Handset Type,572,0.4,object
Handset Manufacturer,572,0.4,object
IMEI,572,0.4,float64
IMSI,570,0.4,float64
Dur. (ms),1,0.0,float64
Total UL (Bytes),1,0.0,float64
Start ms,1,0.0,float64
End,1,0.0,object
End ms,1,0.0,float64
Start,1,0.0,object
Avg Bearer TP DL (kbps),1,0.0,float64
Dur. (ms).1,1,0.0,float64
Activity Duration UL (ms),1,0.0,float64
Activity Duration DL (ms),1,0.0,float64
Avg Bearer TP UL (kbps),1,0.0,float64
Total DL (Bytes),1,0.0,float64

# Drop columns which has > 30% missing values

In [26]:
missing_table['% of Total Values']

Nb of sec with 37500B < Vol UL              86.8
Nb of sec with 6250B < Vol UL < 37500B      74.6
Nb of sec with 125000B < Vol DL             65.0
TCP UL Retrans. Vol (Bytes)                 64.4
Nb of sec with 31250B < Vol DL < 125000B    62.4
Nb of sec with 1250B < Vol UL < 6250B       61.9
Nb of sec with 6250B < Vol DL < 31250B      58.9
TCP DL Retrans. Vol (Bytes)                 58.8
HTTP UL (Bytes)                             54.5
HTTP DL (Bytes)                             54.3
Avg RTT DL (ms)                             18.6
Avg RTT UL (ms)                             18.5
Last Location Name                           0.8
MSISDN/Number                                0.7
Bearer Id                                    0.7
Nb of sec with Vol UL < 1250B                0.5
10 Kbps < UL TP < 50 Kbps (%)                0.5
UL TP > 300 Kbps (%)                         0.5
50 Kbps < UL TP < 300 Kbps (%)               0.5
UL TP < 10 Kbps (%)                          0.5
Nb of sec with Vol DL < 6250B                0.5
250 Kbps < DL TP < 1 Mbps (%)                0.5
50 Kbps < DL TP < 250 Kbps (%)               0.5
DL TP < 50 Kbps (%)                          0.5
DL TP > 1 Mbps (%)                           0.5
Handset Type                                 0.4
Handset Manufacturer                         0.4
IMEI                                         0.4
IMSI                                         0.4
Dur. (ms)                                    0.0
Total UL (Bytes)                             0.0
Start ms                                     0.0
End                                          0.0
End ms                                       0.0
Start                                        0.0
Avg Bearer TP DL (kbps)                      0.0
Dur. (ms).1                                  0.0
Activity Duration UL (ms)                    0.0
Activity Duration DL (ms)                    0.0
Avg Bearer TP UL (kbps)                      0.0
Total DL (Bytes)                             0.0
Name: % of Total Values, dtype: float64

In [27]:
util.percent_missing(df)

(13.0,
 Bearer Id                                      991
 Start                                            1
 Start ms                                         1
 End                                              1
 End ms                                           1
 Dur. (ms)                                        1
 IMSI                                           570
 MSISDN/Number                                 1066
 IMEI                                           572
 Last Location Name                            1153
 Avg RTT DL (ms)                              27829
 Avg RTT UL (ms)                              27812
 Avg Bearer TP DL (kbps)                          1
 Avg Bearer TP UL (kbps)                          1
 TCP DL Retrans. Vol (Bytes)                  88146
 TCP UL Retrans. Vol (Bytes)                  96649
 DL TP < 50 Kbps (%)                            754
 50 Kbps < DL TP < 250 Kbps (%)                 754
 250 Kbps < DL TP < 1 Mbps (%)                  754
 DL TP > 1 Mbps (%)                             754
 UL TP < 10 Kbps (%)                            792
 10 Kbps < UL TP < 50 Kbps (%)                  792
 50 Kbps < UL TP < 300 Kbps (%)                 792
 UL TP > 300 Kbps (%)                           792
 HTTP DL (Bytes)                              81474
 HTTP UL (Bytes)                              81810
 Activity Duration DL (ms)                        1
 Activity Duration UL (ms)                        1
 Dur. (ms).1                                      1
 Handset Manufacturer                           572
 Handset Type                                   572
 Nb of sec with 125000B < Vol DL              97538
 Nb of sec with 1250B < Vol UL < 6250B        92894
 Nb of sec with 31250B < Vol DL < 125000B     93586
 Nb of sec with 37500B < Vol UL              130254
 Nb of sec with 6250B < Vol DL < 31250B       88317
 Nb of sec with 6250B < Vol UL < 37500B      111843
 Nb of sec with Vol DL < 6250B                  755
 Nb of sec with Vol UL < 1250B                  793
 Social Media DL (Bytes)                          0
 Social Media UL (Bytes)                          0
 Google DL (Bytes)                                0
 Google UL (Bytes)                                0
 Email DL (Bytes)                                 0
 Email UL (Bytes)                                 0
 Youtube DL (Bytes)                               0
 Youtube UL (Bytes)                               0
 Netflix DL (Bytes)                               0
 Netflix UL (Bytes)                               0
 Gaming DL (Bytes)                                0
 Gaming UL (Bytes)                                0
 Other DL (Bytes)                                 0
 Other UL (Bytes)                                 0
 Total UL (Bytes)                                 1
 Total DL (Bytes)                                 1
 dtype: int64)

In [28]:
for i in df.columns:
    percent, _ = util.percent_missing(df[i])
    if (percent > 30):
        df = df.drop([i], axis=1)

In [29]:
df.shape
df.columns

Index(['Bearer Id', 'Start', 'Start ms', 'End', 'End ms', 'Dur. (ms)', 'IMSI',
       'MSISDN/Number', 'IMEI', 'Last Location Name', 'Avg RTT DL (ms)',
       'Avg RTT UL (ms)', 'Avg Bearer TP DL (kbps)', 'Avg Bearer TP UL (kbps)',
       'DL TP < 50 Kbps (%)', '50 Kbps < DL TP < 250 Kbps (%)',
       '250 Kbps < DL TP < 1 Mbps (%)', 'DL TP > 1 Mbps (%)',
       'UL TP < 10 Kbps (%)', '10 Kbps < UL TP < 50 Kbps (%)',
       '50 Kbps < UL TP < 300 Kbps (%)', 'UL TP > 300 Kbps (%)',
       'Activity Duration DL (ms)', 'Activity Duration UL (ms)', 'Dur. (ms).1',
       'Handset Manufacturer', 'Handset Type', 'Nb of sec with Vol DL < 6250B',
       'Nb of sec with Vol UL < 1250B', 'Social Media DL (Bytes)',
       'Social Media UL (Bytes)', 'Google DL (Bytes)', 'Google UL (Bytes)',
       'Email DL (Bytes)', 'Email UL (Bytes)', 'Youtube DL (Bytes)',
       'Youtube UL (Bytes)', 'Netflix DL (Bytes)', 'Netflix UL (Bytes)',
       'Gaming DL (Bytes)', 'Gaming UL (Bytes)', 'Other DL (Bytes)',
       'Other UL (Bytes)', 'Total UL (Bytes)', 'Total DL (Bytes)'],
      dtype='object')

In [30]:
missing_table = util.missing_values_table(df)
missing_table

                                Missing Values  % of Total Values    Dtype
Avg RTT DL (ms)                          27829               18.6  float64
Avg RTT UL (ms)                          27812               18.5  float64
Last Location Name                        1153                0.8   object
MSISDN/Number                             1066                0.7  float64
Bearer Id                                  991                0.7  float64
Nb of sec with Vol UL < 1250B              793                0.5  float64
UL TP > 300 Kbps (%)                       792                0.5  float64
50 Kbps < UL TP < 300 Kbps (%)             792                0.5  float64
10 Kbps < UL TP < 50 Kbps (%)              792                0.5  float64
UL TP < 10 Kbps (%)                        792                0.5  float64
Nb of sec with Vol DL < 6250B              755                0.5  float64
DL TP < 50 Kbps (%)                        754                0.5  float64
DL TP > 1 Mbps (%)                         754                0.5  float64
250 Kbps < DL TP < 1 Mbps (%)              754                0.5  float64
50 Kbps < DL TP < 250 Kbps (%)             754                0.5  float64
IMEI                                       572                0.4  float64
Handset Manufacturer                       572                0.4   object
Handset Type                               572                0.4   object
IMSI                                       570                0.4  float64
Start                                        1                0.0   object
Avg Bearer TP UL (kbps)                      1                0.0  float64
Avg Bearer TP DL (kbps)                      1                0.0  float64
Dur. (ms)                                    1                0.0  float64
End ms                                       1                0.0  float64
Activity Duration DL (ms)                    1                0.0  float64
Activity Duration UL (ms)                    1                0.0  float64
Dur. (ms).1                                  1                0.0  float64
End                                          1                0.0   object
Start ms                                     1                0.0  float64
Total UL (Bytes)                             1                0.0  float64
Total DL (Bytes)                             1                0.0  float64

### If the data is not skewed, filling with either mean or median will work well. But if it is indeed skew, then fill with Median.

In [31]:
du = DataUnderstanding(df)
du.get_skew()

Bearer Id                           0.026666
Start ms                            0.000968
End ms                             -0.001163
Dur. (ms)                           3.952609
IMSI                               41.045956
MSISDN/Number                     332.155856
IMEI                                1.071470
Avg RTT DL (ms)                    62.907828
Avg RTT UL (ms)                    28.457415
Avg Bearer TP DL (kbps)             2.589437
Avg Bearer TP UL (kbps)             4.503413
DL TP < 50 Kbps (%)                -2.297803
50 Kbps < DL TP < 250 Kbps (%)      3.271453
250 Kbps < DL TP < 1 Mbps (%)       4.566158
DL TP > 1 Mbps (%)                  5.370351
UL TP < 10 Kbps (%)                -8.985016
10 Kbps < UL TP < 50 Kbps (%)      10.943888
50 Kbps < UL TP < 300 Kbps (%)     21.878495
UL TP > 300 Kbps (%)               36.174053
Activity Duration DL (ms)           5.872256
Activity Duration UL (ms)           7.382557
Dur. (ms).1                         3.952609
Nb of sec with Vol DL < 6250B       9.042166
Nb of sec with Vol UL < 1250B       7.495176
Social Media DL (Bytes)            -0.002136
Social Media UL (Bytes)            -0.000359
Google DL (Bytes)                  -0.008092
Google UL (Bytes)                   0.002216
Email DL (Bytes)                   -0.002463
Email UL (Bytes)                    0.007358
Youtube DL (Bytes)                  0.000231
Youtube UL (Bytes)                 -0.001142
Netflix DL (Bytes)                 -0.002442
Netflix UL (Bytes)                 -0.000113
Gaming DL (Bytes)                  -0.003460
Gaming UL (Bytes)                  -0.001840
Other DL (Bytes)                    0.001400
Other UL (Bytes)                    0.001392
Total UL (Bytes)                   -0.002456
Total DL (Bytes)                   -0.003153
dtype: float64

In [32]:
for i in df.columns:
    _, count = util.percent_missing(df[i])
    if count > 0:
        if df[i].dtype == 'object':
            df[i] = df[i].fillna(df[i].mode()[0])
        elif df[i].dtype == 'float64' and df[i].skew(axis=0) != 0:
            df[i] = df[i].fillna(df[i].mode()[0])
        elif df[i].dtype == 'float64' and df[i].skew(axis=0) == 0:
            df[i] = df[i].fillna(df[i].mean())

In [33]:
missing_table = util.missing_values_table(df)
missing_table

Empty DataFrame
Columns: [Missing Values, % of Total Values, Dtype]
Index: []

In [34]:
util.save_data(df, "../data/clean_data.csv")
df.shape

(150001, 45)